[package]
name = "composer"
version = "0.1.0"
authors = ["Matt Garnett <14004106+lightclient@users.noreply.github.com>"]
edition = "2018"

[dependencies]
arrayref = "0.3.5"
bigint = "4.4.1"
rand = "0.7"
sha2 = "0.8.0"
hex = "0.3.2"
imp = "0.0.1"
sheth = { path = "../", features = ["std"] }
